"""Request ID / correlation ID contract (docs/05-api/api-contract.md §28)."""

import logging


def test_client_supplied_valid_request_id_is_honored(probe_client) -> None:
    response = probe_client.get("/probe/abc", headers={"X-Request-ID": "client-supplied-id-123"})

    assert response.status_code == 200
    assert response.headers["X-Request-ID"] == "client-supplied-id-123"


def test_client_supplied_request_id_is_honored_in_error_response(probe_client) -> None:
    response = probe_client.get(
        "/probe-error/404", headers={"X-Request-ID": "client-supplied-id-456"}
    )

    assert response.status_code == 404
    assert response.headers["X-Request-ID"] == "client-supplied-id-456"
    assert response.json()["error"]["request_id"] == "client-supplied-id-456"


def test_invalid_client_request_id_is_replaced_with_a_generated_one(probe_client) -> None:
    invalid_id = "not a valid header value \x00 with spaces and control chars"
    response = probe_client.get("/probe/abc", headers={"X-Request-ID": invalid_id})

    assert response.status_code == 200
    generated = response.headers["X-Request-ID"]
    assert generated != invalid_id
    assert generated  # non-empty


def test_request_id_is_autogenerated_when_absent(probe_client) -> None:
    response = probe_client.get("/probe/abc")

    assert response.status_code == 200
    assert response.headers.get("X-Request-ID")


def test_request_id_appears_in_logs(probe_client, caplog) -> None:
    with caplog.at_level(logging.INFO, logger="tourcrm.api"):
        response = probe_client.get(
            "/probe/abc", headers={"X-Request-ID": "log-visible-request-id"}
        )

    assert response.status_code == 200
    assert any("log-visible-request-id" in record.message for record in caplog.records)
