"""create attendance table

Revision ID: 0bada762f164
Revises: 9888ee04d9db
Create Date: 2026-09-15 18:12:18.482173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bada762f164'
down_revision: Union[str, None] = '9888ee04d9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ADR-0032 §11 amends ADR-0024 §4's closed audit action vocabulary with 4
# new Attendance action codes. Alembic's autogenerate does not diff CHECK
# constraint bodies, so this swap is hand-written, matching the precedent
# in 9888ee04d9db_create_event_series_relationship_source_.py.
_OLD_ACTION_VALUES = (
    "'event.archived','event.created','event.status_changed','event.updated',"
    "'event_occurrence.exception_changed','event_occurrence.exception_created',"
    "'event_occurrence.series_rebound','event_occurrence.status_changed',"
    "'event_occurrence_group_target.changed','event_occurrence_group_target.created',"
    "'event_occurrence_group_target.ended','event_occurrence_participant.changed',"
    "'event_occurrence_participant.created','event_occurrence_participant.ended',"
    "'event_occurrence_staff_assignment.changed','event_occurrence_staff_assignment.created',"
    "'event_occurrence_staff_assignment.ended','event_series.created',"
    "'event_series.status_changed','event_series.updated','event_series.version_created',"
    "'event_series_group_target.changed','event_series_group_target.created',"
    "'event_series_group_target.ended','event_series_participant.changed',"
    "'event_series_participant.created','event_series_participant.ended',"
    "'event_series_staff_assignment.changed','event_series_staff_assignment.created',"
    "'event_series_staff_assignment.ended','group.created','group.updated',"
    "'group_instructor_assignment.created','group_instructor_assignment.ended',"
    "'group_instructor_assignment.updated','group_membership.created',"
    "'group_membership.ended','group_membership.updated','guardian_relationship.created',"
    "'guardian_relationship.revoked','guardian_relationship.updated','membership.created',"
    "'membership.ended','membership.status_changed','membership.updated',"
    "'person.archived','person.created','person.updated','role_assignment.changed',"
    "'role_assignment.created','role_assignment.revoked','user.created','user.locked',"
    "'user.status_changed','user.unlocked'"
)
_NEW_ACTION_VALUES = (
    "'attendance.bulk_changed','attendance.changed','attendance.corrected',"
    "'attendance.created','event.archived','event.created','event.status_changed',"
    "'event.updated','event_occurrence.exception_changed',"
    "'event_occurrence.exception_created','event_occurrence.series_rebound',"
    "'event_occurrence.status_changed','event_occurrence_group_target.changed',"
    "'event_occurrence_group_target.created','event_occurrence_group_target.ended',"
    "'event_occurrence_participant.changed','event_occurrence_participant.created',"
    "'event_occurrence_participant.ended','event_occurrence_staff_assignment.changed',"
    "'event_occurrence_staff_assignment.created','event_occurrence_staff_assignment.ended',"
    "'event_series.created','event_series.status_changed','event_series.updated',"
    "'event_series.version_created','event_series_group_target.changed',"
    "'event_series_group_target.created','event_series_group_target.ended',"
    "'event_series_participant.changed','event_series_participant.created',"
    "'event_series_participant.ended','event_series_staff_assignment.changed',"
    "'event_series_staff_assignment.created','event_series_staff_assignment.ended',"
    "'group.created','group.updated','group_instructor_assignment.created',"
    "'group_instructor_assignment.ended','group_instructor_assignment.updated',"
    "'group_membership.created','group_membership.ended','group_membership.updated',"
    "'guardian_relationship.created','guardian_relationship.revoked',"
    "'guardian_relationship.updated','membership.created','membership.ended',"
    "'membership.status_changed','membership.updated','person.archived','person.created',"
    "'person.updated','role_assignment.changed','role_assignment.created',"
    "'role_assignment.revoked','user.created','user.locked','user.status_changed',"
    "'user.unlocked'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('absence_reason', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("absence_reason IS NULL OR absence_reason IN ('sick','family_reason','injury','education','work','other')", name='ck_attendance_absence_reason_valid'),
    sa.CheckConstraint("status = 'absent' OR (absence_reason IS NULL AND comment IS NULL)", name='ck_attendance_present_has_no_reason_or_comment'),
    sa.CheckConstraint("status IN ('present','absent')", name='ck_attendance_status_valid'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['event_occurrences.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occurrence_id', 'person_id', name='uq_attendance_occurrence_id_person_id')
    )
    op.create_index('ix_attendance_person_id', 'attendance', ['person_id'], unique=False)
    # ### end Alembic commands ###

    op.drop_constraint('ck_audit_logs_action_valid', 'audit_logs', type_='check')
    op.create_check_constraint(
        'ck_audit_logs_action_valid', 'audit_logs', f'action IN ({_NEW_ACTION_VALUES})'
    )


def downgrade() -> None:
    op.drop_constraint('ck_audit_logs_action_valid', 'audit_logs', type_='check')
    op.create_check_constraint(
        'ck_audit_logs_action_valid', 'audit_logs', f'action IN ({_OLD_ACTION_VALUES})'
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_person_id', table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
