"""add trip duration classification

Revision ID: 12de408aee0d
Revises: 2c28e7b34462
Create Date: 2026-10-05 16:53:02.355290


Issue #274 (Tourism Facts v2 — Duration Classification Foundation),
canonical source docs/04-modules/trips-and-tourist-profile.md §10:

- adds `trips.duration_classification` — NOT NULL, server default
  `UNCLASSIFIED` (existing Trips become `UNCLASSIFIED`: classification
  not set), CHECK `ck_trips_duration_classification` limits it to
  `ONE_DAY`/`MULTI_DAY`/`UNCLASSIFIED`.

No start/end columns: Event.start_at/end_at stay the only planned
interval. No permission is seeded.

Downgrade drops the constraint and the column.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12de408aee0d'
down_revision: Union[str, None] = '2c28e7b34462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('duration_classification', sa.String(length=16), server_default='UNCLASSIFIED', nullable=False))
    op.create_check_constraint(
        'ck_trips_duration_classification',
        'trips',
        "duration_classification IN ('ONE_DAY', 'MULTI_DAY', 'UNCLASSIFIED')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_trips_duration_classification', 'trips', type_='check')
    op.drop_column('trips', 'duration_classification')
    # ### end Alembic commands ###
