"""create event group target table

Revision ID: 2ba3556a97ce
Revises: e5859c9b98a6
Create Date: 2026-09-13 12:26:33.740153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba3556a97ce'
down_revision: Union[str, None] = 'e5859c9b98a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_group_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_event_group_targets_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_group_targets_event_id_valid_from_valid_to', 'event_group_targets', ['event_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_event_group_targets_group_id_valid_from_valid_to', 'event_group_targets', ['group_id', 'valid_from', 'valid_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_group_targets_group_id_valid_from_valid_to', table_name='event_group_targets')
    op.drop_index('ix_event_group_targets_event_id_valid_from_valid_to', table_name='event_group_targets')
    op.drop_table('event_group_targets')
    # ### end Alembic commands ###
