"""create inventory instances

Revision ID: 315a43d40d9b
Revises: a3872eb0b9d7
Create Date: 2026-09-30 19:52:11.035898

Inventory Slice 2 — instances (Issue #230, docs/04-domain/inventory.md §7,
§13, §16):

- `inventory_instances`: one physical object of an `instance`-mode item.
  `inventory_number` (`INV-000123`, CHECK format) is unique; `state` is the
  closed `available`/`issued`/`in_repair`/`written_off` set; the storage
  location is set exactly for `available`/`in_repair` (CHECK, R3). Every
  FK is RESTRICT — instances are never deleted.
- `inventory_movements` gains `instance_id`, `from_location_id`,
  `to_location_id`, `unit_cost_minor` (only on `receipt`, >= 0) and
  `comment`; the movement-type CHECK adds `repair_start`/`repair_end`,
  which require an instance.

No permission is seeded; no existing row changes meaning (no movement
exists before this slice's workflows).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315a43d40d9b'
down_revision: Union[str, None] = 'a3872eb0b9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('inventory_number', sa.String(length=32), nullable=False),
    sa.Column('manufacturer_barcode', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_serial_number', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('storage_location_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(state IN ('available','in_repair')) = (storage_location_id IS NOT NULL)", name='ck_inventory_instances_location_matches_state'),
    sa.CheckConstraint("inventory_number ~ '^INV-[0-9]{6,}$'", name='ck_inventory_instances_inventory_number_format'),
    sa.CheckConstraint("state IN ('available','in_repair','issued','written_off')", name='ck_inventory_instances_state_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['inventory_storage_locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_number', name='uq_inventory_instances_inventory_number')
    )
    op.create_index('ix_inventory_instances_item_id_state', 'inventory_instances', ['item_id', 'state'], unique=False)
    op.create_index('ix_inventory_instances_state', 'inventory_instances', ['state'], unique=False)
    op.create_index('ix_inventory_instances_storage_location_id', 'inventory_instances', ['storage_location_id'], unique=False)
    op.add_column('inventory_movements', sa.Column('instance_id', sa.UUID(), nullable=True))
    op.add_column('inventory_movements', sa.Column('from_location_id', sa.UUID(), nullable=True))
    op.add_column('inventory_movements', sa.Column('to_location_id', sa.UUID(), nullable=True))
    op.add_column('inventory_movements', sa.Column('unit_cost_minor', sa.BigInteger(), nullable=True))
    op.add_column('inventory_movements', sa.Column('comment', sa.Text(), nullable=True))
    op.create_index('ix_inventory_movements_instance_id_created_at', 'inventory_movements', ['instance_id', 'created_at'], unique=False)
    op.create_foreign_key('inventory_movements_to_location_id_fkey', 'inventory_movements', 'inventory_storage_locations', ['to_location_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('inventory_movements_from_location_id_fkey', 'inventory_movements', 'inventory_storage_locations', ['from_location_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('inventory_movements_instance_id_fkey', 'inventory_movements', 'inventory_instances', ['instance_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    # CHECK constraints are not compared by autogenerate.
    op.drop_constraint('ck_inventory_movements_movement_type_valid', 'inventory_movements', type_='check')
    op.create_check_constraint(
        'ck_inventory_movements_movement_type_valid',
        'inventory_movements',
        "movement_type IN ('adjustment','issue','receipt','repair_end','repair_start','return','transfer','write_off','writeoff_reversal')",
    )
    op.create_check_constraint(
        'ck_inventory_movements_instance_only_types',
        'inventory_movements',
        "movement_type NOT IN ('repair_end','repair_start') OR instance_id IS NOT NULL",
    )
    op.create_check_constraint(
        'ck_inventory_movements_unit_cost_on_receipt',
        'inventory_movements',
        "unit_cost_minor IS NULL OR (movement_type = 'receipt' AND unit_cost_minor >= 0)",
    )


def downgrade() -> None:
    op.drop_constraint('ck_inventory_movements_unit_cost_on_receipt', 'inventory_movements', type_='check')
    op.drop_constraint('ck_inventory_movements_instance_only_types', 'inventory_movements', type_='check')
    op.drop_constraint('ck_inventory_movements_movement_type_valid', 'inventory_movements', type_='check')
    op.create_check_constraint(
        'ck_inventory_movements_movement_type_valid',
        'inventory_movements',
        "movement_type IN ('adjustment','issue','receipt','return','transfer','write_off','writeoff_reversal')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_movements_instance_id_fkey', 'inventory_movements', type_='foreignkey')
    op.drop_constraint('inventory_movements_from_location_id_fkey', 'inventory_movements', type_='foreignkey')
    op.drop_constraint('inventory_movements_to_location_id_fkey', 'inventory_movements', type_='foreignkey')
    op.drop_index('ix_inventory_movements_instance_id_created_at', table_name='inventory_movements')
    op.drop_column('inventory_movements', 'comment')
    op.drop_column('inventory_movements', 'unit_cost_minor')
    op.drop_column('inventory_movements', 'to_location_id')
    op.drop_column('inventory_movements', 'from_location_id')
    op.drop_column('inventory_movements', 'instance_id')
    op.drop_index('ix_inventory_instances_storage_location_id', table_name='inventory_instances')
    op.drop_index('ix_inventory_instances_state', table_name='inventory_instances')
    op.drop_index('ix_inventory_instances_item_id_state', table_name='inventory_instances')
    op.drop_table('inventory_instances')
    # ### end Alembic commands ###
