"""create notification and outbox tables

Revision ID: 8c7a78e7178a
Revises: 3b1fd730bb0d
Create Date: 2026-10-08 10:54:02.511541

Issue #318 — Notification Center persistence foundation (ADR-0045 §3,
ADR-0046 §5, docs/03-architecture/database-schema.md §18):

- `notification_templates`, `notification_rules` (one rule per
  club/event/channel/recipient scope, NULLS NOT DISTINCT for the
  installation-wide rule), `communication_preferences` (one per
  user/channel/notification type; quiet hours all-or-none);
- `notifications`: logical message to one recipient, globally UNIQUE
  `idempotency_key`;
- `notification_deliveries`: channel-specific delivery state, UNIQUE per
  (notification, channel, destination), internal destination reference
  only, CHECK-consistent attempt/delivered timestamps;
- `telegram_destinations`: routing identity `chat_id` + nullable
  `message_thread_id` (UNIQUE, NULLS NOT DISTINCT); topic name is
  metadata only;
- `outbox_jobs`: the generic PostgreSQL-backed transactional outbox —
  status/attempts/next_attempt_at/lease (`locked_by`, `locked_until`)/
  terminal `dead` state, optional UNIQUE `deduplication_key`, and two
  partial indexes for the future `FOR UPDATE SKIP LOCKED` claim and
  expired-lease scans.

No secret/credential column, no seed data, no permission or role grant.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c7a78e7178a'
down_revision: Union[str, None] = '3b1fd730bb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('subject_template', sa.Text(), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(body_template) <> ''", name='ck_notification_templates_body_not_blank'),
    sa.CheckConstraint("btrim(code) <> ''", name='ck_notification_templates_code_not_blank'),
    sa.CheckConstraint("btrim(locale) <> ''", name='ck_notification_templates_locale_not_blank'),
    sa.CheckConstraint("channel IN ('email','telegram')", name='ck_notification_templates_channel_valid'),
    sa.CheckConstraint('version >= 1', name='ck_notification_templates_version_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_notification_templates_code')
    )
    op.create_table('outbox_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deduplication_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.String(length=1024), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'processing') = (locked_until IS NOT NULL)", name='ck_outbox_jobs_lease_iff_processing'),
    sa.CheckConstraint("(status IN ('completed','dead')) = (finished_at IS NOT NULL)", name='ck_outbox_jobs_finished_at_iff_terminal'),
    sa.CheckConstraint("btrim(job_type) <> ''", name='ck_outbox_jobs_job_type_not_blank'),
    sa.CheckConstraint("deduplication_key IS NULL OR btrim(deduplication_key) <> ''", name='ck_outbox_jobs_deduplication_key_not_blank'),
    sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name='ck_outbox_jobs_payload_is_object'),
    sa.CheckConstraint("status IN ('completed','dead','pending','processing')", name='ck_outbox_jobs_status_valid'),
    sa.CheckConstraint('(locked_by IS NULL) = (locked_until IS NULL)', name='ck_outbox_jobs_lease_owner_and_expiry_together'),
    sa.CheckConstraint('attempts >= 0', name='ck_outbox_jobs_attempts_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_key', name='uq_outbox_jobs_deduplication_key')
    )
    op.create_index('ix_outbox_jobs_pending_next_attempt_at', 'outbox_jobs', ['next_attempt_at', 'id'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_outbox_jobs_processing_locked_until', 'outbox_jobs', ['locked_until'], unique=False, postgresql_where=sa.text("status = 'processing'"))
    op.create_table('notification_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('recipient_scope', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('scheduling', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(event_type) <> ''", name='ck_notification_rules_event_type_not_blank'),
    sa.CheckConstraint("btrim(recipient_scope) <> ''", name='ck_notification_rules_recipient_scope_not_blank'),
    sa.CheckConstraint("channel IN ('email','telegram')", name='ck_notification_rules_channel_valid'),
    sa.CheckConstraint("scheduling IS NULL OR jsonb_typeof(scheduling) = 'object'", name='ck_notification_rules_scheduling_is_object'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'event_type', 'channel', 'recipient_scope', name='uq_notification_rules_club_event_channel_scope', postgresql_nulls_not_distinct=True)
    )
    op.create_table('telegram_destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_name', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notification_scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(name) <> ''", name='ck_telegram_destinations_name_not_blank'),
    sa.CheckConstraint("jsonb_typeof(notification_scope) = 'object'", name='ck_telegram_destinations_notification_scope_is_object'),
    sa.CheckConstraint('chat_id <> 0', name='ck_telegram_destinations_chat_id_non_zero'),
    sa.CheckConstraint('message_thread_id IS NULL OR message_thread_id > 0', name='ck_telegram_destinations_message_thread_id_positive'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'message_thread_id', name='uq_telegram_destinations_chat_id_message_thread_id', postgresql_nulls_not_distinct=True)
    )
    op.create_table('communication_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('quiet_hours_timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(notification_type) <> ''", name='ck_communication_preferences_notification_type_not_blank'),
    sa.CheckConstraint("channel IN ('email','telegram')", name='ck_communication_preferences_channel_valid'),
    sa.CheckConstraint('(quiet_hours_start IS NULL) = (quiet_hours_end IS NULL) AND (quiet_hours_start IS NULL) = (quiet_hours_timezone IS NULL)', name='ck_communication_preferences_quiet_hours_complete'),
    sa.CheckConstraint('quiet_hours_start IS NULL OR quiet_hours_start <> quiet_hours_end', name='ck_communication_preferences_quiet_hours_non_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel', 'notification_type', name='uq_communication_preferences_user_channel_type')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("btrim(event_type) <> ''", name='ck_notifications_event_type_not_blank'),
    sa.CheckConstraint("btrim(idempotency_key) <> ''", name='ck_notifications_idempotency_key_not_blank'),
    sa.CheckConstraint("btrim(subject_type) <> ''", name='ck_notifications_subject_type_not_blank'),
    sa.CheckConstraint("status IN ('cancelled','pending','processed','skipped')", name='ck_notifications_status_valid'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_notifications_idempotency_key')
    )
    op.create_index('ix_notifications_club_id_created_at', 'notifications', ['club_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_recipient_user_id_created_at', 'notifications', ['recipient_user_id', 'created_at'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('destination_type', sa.String(length=32), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'delivered') = (delivered_at IS NOT NULL)", name='ck_notification_deliveries_delivered_at_iff_delivered'),
    sa.CheckConstraint("channel IN ('email','telegram')", name='ck_notification_deliveries_channel_valid'),
    sa.CheckConstraint("destination_type <> 'telegram_destination' OR channel = 'telegram'", name='ck_notification_deliveries_telegram_destination_channel'),
    sa.CheckConstraint("destination_type IN ('telegram_destination','user')", name='ck_notification_deliveries_destination_type_valid'),
    sa.CheckConstraint("status IN ('cancelled','delivered','failed','pending','processing','skipped')", name='ck_notification_deliveries_status_valid'),
    sa.CheckConstraint('(attempts = 0) = (first_attempt_at IS NULL)', name='ck_notification_deliveries_first_attempt_iff_attempted'),
    sa.CheckConstraint('(first_attempt_at IS NULL) = (last_attempt_at IS NULL)', name='ck_notification_deliveries_attempt_timestamps_together'),
    sa.CheckConstraint('attempts >= 0', name='ck_notification_deliveries_attempts_non_negative'),
    sa.CheckConstraint('last_attempt_at IS NULL OR last_attempt_at >= first_attempt_at', name='ck_notification_deliveries_attempt_timestamps_ordered'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'channel', 'destination_type', 'destination_id', name='uq_notification_deliveries_notification_channel_destination')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_deliveries')
    op.drop_index('ix_notifications_recipient_user_id_created_at', table_name='notifications')
    op.drop_index('ix_notifications_club_id_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('communication_preferences')
    op.drop_table('telegram_destinations')
    op.drop_table('notification_rules')
    op.drop_index('ix_outbox_jobs_processing_locked_until', table_name='outbox_jobs', postgresql_where=sa.text("status = 'processing'"))
    op.drop_index('ix_outbox_jobs_pending_next_attempt_at', table_name='outbox_jobs', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('outbox_jobs')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
