"""add event recurrence series occurrence exception tables

Revision ID: 8de091605703
Revises: 7d1ba37672bd
Create Date: 2026-09-14 21:33:06.737290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8de091605703'
down_revision: Union[str, None] = '7d1ba37672bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ADR-0028 amends ADR-0024 §4's closed audit action vocabulary with the
# eight recurrence action codes. Alembic's autogenerate does not diff CHECK
# constraint bodies, so this swap is hand-written, matching the precedent
# in b99fd408c104_add_club_membership_indexes_and_extend_.py.
_OLD_ACTION_VALUES = (
    "'event.archived','event.created','event.status_changed','event.updated',"
    "'group.created','group.updated','group_instructor_assignment.created',"
    "'group_instructor_assignment.ended','group_instructor_assignment.updated',"
    "'group_membership.created','group_membership.ended','group_membership.updated',"
    "'guardian_relationship.created','guardian_relationship.revoked',"
    "'guardian_relationship.updated','membership.created','membership.ended',"
    "'membership.status_changed','membership.updated','person.archived',"
    "'person.created','person.updated','role_assignment.changed',"
    "'role_assignment.created','role_assignment.revoked','user.created','user.locked',"
    "'user.status_changed','user.unlocked'"
)
_NEW_ACTION_VALUES = (
    "'event.archived','event.created','event.status_changed','event.updated',"
    "'event_occurrence.exception_changed','event_occurrence.exception_created',"
    "'event_occurrence.series_rebound','event_occurrence.status_changed',"
    "'event_series.created','event_series.status_changed','event_series.updated',"
    "'event_series.version_created',"
    "'group.created','group.updated','group_instructor_assignment.created',"
    "'group_instructor_assignment.ended','group_instructor_assignment.updated',"
    "'group_membership.created','group_membership.ended','group_membership.updated',"
    "'guardian_relationship.created','guardian_relationship.revoked',"
    "'guardian_relationship.updated','membership.created','membership.ended',"
    "'membership.status_changed','membership.updated','person.archived',"
    "'person.created','person.updated','role_assignment.changed',"
    "'role_assignment.created','role_assignment.revoked','user.created','user.locked',"
    "'user.status_changed','user.unlocked'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('root_series_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_series_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('series_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('series_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurrence_limit', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('recurrence_rule', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('lesson','training','trip','competition','tour_slet','excursion','meeting','other')", name='ck_event_series_event_type_valid'),
    sa.CheckConstraint("status IN ('active','paused','cancelled','archived')", name='ck_event_series_status_valid'),
    sa.CheckConstraint('occurrence_limit IS NULL OR occurrence_limit > 0', name='ck_event_series_occurrence_limit_positive'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_event_series_duration_minutes_positive'),
    sa.CheckConstraint('series_end_at IS NULL OR series_end_at > series_start_at', name='ck_event_series_end_at_after_start_at'),
    sa.CheckConstraint('version > 0', name='ck_event_series_version_positive'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['root_series_id'], ['event_series.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_series_id'], ['event_series.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_series_id', 'version', name='uq_event_series_root_series_id_version'),
    sa.UniqueConstraint('supersedes_series_id', name='uq_event_series_one_successor_per_predecessor')
    )
    op.create_index('ix_event_series_club_id_status', 'event_series', ['club_id', 'status'], unique=False)
    op.create_index('ix_event_series_root_series_id', 'event_series', ['root_series_id'], unique=False)
    op.create_table('event_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('recurrence_anchor_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('lesson','training','trip','competition','tour_slet','excursion','meeting','other')", name='ck_event_occurrences_event_type_valid'),
    sa.CheckConstraint("status <> 'cancelled' OR cancellation_reason IS NOT NULL", name='ck_event_occurrences_cancellation_reason_required'),
    sa.CheckConstraint("status IN ('scheduled','in_progress','completed','cancelled')", name='ck_event_occurrences_status_valid'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_event_occurrences_ends_at_after_starts_at'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['series_id'], ['event_series.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'recurrence_anchor_at', name='uq_event_occurrences_series_id_recurrence_anchor_at')
    )
    op.create_index('ix_event_occurrences_club_id_starts_at', 'event_occurrences', ['club_id', 'starts_at'], unique=False)
    op.create_index('ix_event_occurrences_series_id', 'event_occurrences', ['series_id'], unique=False)
    op.create_table('event_occurrence_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=False),
    sa.Column('exception_type', sa.String(length=16), nullable=False),
    sa.Column('original_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("exception_type <> 'cancelled' OR cancellation_reason IS NOT NULL", name='ck_event_occurrence_exceptions_cancellation_reason_required'),
    sa.CheckConstraint("exception_type IN ('rescheduled','cancelled')", name='ck_event_occurrence_exceptions_exception_type_valid'),
    sa.CheckConstraint('effective_start_at IS NULL OR effective_end_at IS NULL OR effective_end_at > effective_start_at', name='ck_event_occurrence_exceptions_effective_end_after_start'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['event_occurrences.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occurrence_id')
    )
    # ### end Alembic commands ###

    op.drop_constraint('ck_audit_logs_action_valid', 'audit_logs', type_='check')
    op.create_check_constraint(
        'ck_audit_logs_action_valid', 'audit_logs', f'action IN ({_NEW_ACTION_VALUES})'
    )


def downgrade() -> None:
    op.drop_constraint('ck_audit_logs_action_valid', 'audit_logs', type_='check')
    op.create_check_constraint(
        'ck_audit_logs_action_valid', 'audit_logs', f'action IN ({_OLD_ACTION_VALUES})'
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_occurrence_exceptions')
    op.drop_index('ix_event_occurrences_series_id', table_name='event_occurrences')
    op.drop_index('ix_event_occurrences_club_id_starts_at', table_name='event_occurrences')
    op.drop_table('event_occurrences')
    op.drop_index('ix_event_series_root_series_id', table_name='event_series')
    op.drop_index('ix_event_series_club_id_status', table_name='event_series')
    op.drop_table('event_series')
    # ### end Alembic commands ###
