"""make event occurrence support non-recurring events

Revision ID: 91a40113d17b
Revises: 0bada762f164
Create Date: 2026-09-15 18:47:41.765376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a40113d17b'
down_revision: Union[str, None] = '0bada762f164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_occurrences', sa.Column('event_id', sa.UUID(), nullable=True))
    op.alter_column('event_occurrences', 'series_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_event_occurrences_event_id', 'event_occurrences', ['event_id'], unique=False)
    op.create_unique_constraint('uq_event_occurrences_event_id', 'event_occurrences', ['event_id'])
    op.create_foreign_key(
        'fk_event_occurrences_event_id_events',
        'event_occurrences', 'events', ['event_id'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###

    # ADR-0033 §2: exactly one of series_id/event_id. Hand-written —
    # autogenerate does not diff CHECK constraint bodies.
    op.create_check_constraint(
        'ck_event_occurrences_exactly_one_source',
        'event_occurrences',
        '(series_id IS NULL) <> (event_id IS NULL)',
    )


def downgrade() -> None:
    op.drop_constraint('ck_event_occurrences_exactly_one_source', 'event_occurrences', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_event_occurrences_event_id_events', 'event_occurrences', type_='foreignkey')
    op.drop_constraint('uq_event_occurrences_event_id', 'event_occurrences', type_='unique')
    op.drop_index('ix_event_occurrences_event_id', table_name='event_occurrences')
    op.alter_column('event_occurrences', 'series_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('event_occurrences', 'event_id')
    # ### end Alembic commands ###
