"""create event series relationship source and occurrence relationship tables

Revision ID: 9888ee04d9db
Revises: 8de091605703
Create Date: 2026-09-15 09:45:11.374031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9888ee04d9db'
down_revision: Union[str, None] = '8de091605703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ADR-0030 amends ADR-0024 §4's closed audit action vocabulary with 15 new
# EventSeries-relationship-source / EventOccurrence-relationship-override
# action codes. Alembic's autogenerate does not diff CHECK constraint
# bodies, so this swap is hand-written, matching the precedent in
# 8de091605703_add_event_recurrence_series_occurrence_.py.
_OLD_ACTION_VALUES = (
    "'event.archived','event.created','event.status_changed','event.updated',"
    "'event_occurrence.exception_changed','event_occurrence.exception_created',"
    "'event_occurrence.series_rebound','event_occurrence.status_changed',"
    "'event_series.created','event_series.status_changed','event_series.updated',"
    "'event_series.version_created','group.created','group.updated',"
    "'group_instructor_assignment.created','group_instructor_assignment.ended',"
    "'group_instructor_assignment.updated','group_membership.created',"
    "'group_membership.ended','group_membership.updated','guardian_relationship.created',"
    "'guardian_relationship.revoked','guardian_relationship.updated','membership.created',"
    "'membership.ended','membership.status_changed','membership.updated',"
    "'person.archived','person.created','person.updated','role_assignment.changed',"
    "'role_assignment.created','role_assignment.revoked','user.created','user.locked',"
    "'user.status_changed','user.unlocked'"
)
_NEW_ACTION_VALUES = (
    "'event.archived','event.created','event.status_changed','event.updated',"
    "'event_occurrence.exception_changed','event_occurrence.exception_created',"
    "'event_occurrence.series_rebound','event_occurrence.status_changed',"
    "'event_occurrence_group_target.changed','event_occurrence_group_target.created',"
    "'event_occurrence_group_target.ended','event_occurrence_participant.changed',"
    "'event_occurrence_participant.created','event_occurrence_participant.ended',"
    "'event_occurrence_staff_assignment.changed','event_occurrence_staff_assignment.created',"
    "'event_occurrence_staff_assignment.ended','event_series.created',"
    "'event_series.status_changed','event_series.updated','event_series.version_created',"
    "'event_series_group_target.changed','event_series_group_target.created',"
    "'event_series_group_target.ended','event_series_participant.changed',"
    "'event_series_participant.created','event_series_participant.ended',"
    "'event_series_staff_assignment.changed','event_series_staff_assignment.created',"
    "'event_series_staff_assignment.ended','group.created','group.updated',"
    "'group_instructor_assignment.created','group_instructor_assignment.ended',"
    "'group_instructor_assignment.updated','group_membership.created',"
    "'group_membership.ended','group_membership.updated','guardian_relationship.created',"
    "'guardian_relationship.revoked','guardian_relationship.updated','membership.created',"
    "'membership.ended','membership.status_changed','membership.updated',"
    "'person.archived','person.created','person.updated','role_assignment.changed',"
    "'role_assignment.created','role_assignment.revoked','user.created','user.locked',"
    "'user.status_changed','user.unlocked'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_series_group_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_series_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_event_series_group_targets_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['event_series_id'], ['event_series.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_series_group_targets_group_id_valid_from_valid_to', 'event_series_group_targets', ['group_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_event_series_group_targets_series_id_valid_from_valid_to', 'event_series_group_targets', ['event_series_id', 'valid_from', 'valid_to'], unique=False)
    op.create_table('event_series_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_series_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('registration_status', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_event_series_participants_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['event_series_id'], ['event_series.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_series_participants_event_series_id', 'event_series_participants', ['event_series_id'], unique=False)
    op.create_index('ix_event_series_participants_person_id', 'event_series_participants', ['person_id'], unique=False)
    op.create_table('event_series_staff_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_series_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_event', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('event_series_id'), '='), (sa.text('tstzrange(valid_from, valid_to)'), '&&'), where=sa.text('is_primary = true'), using='gist', name='ck_event_series_staff_assignments_one_active_primary'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_event_series_staff_assignments_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['event_series_id'], ['event_series.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_series_staff_assignments_event_series_id', 'event_series_staff_assignments', ['event_series_id'], unique=False)
    op.create_index('ix_event_series_staff_assignments_user_id', 'event_series_staff_assignments', ['user_id'], unique=False)
    op.create_table('event_occurrence_group_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_event_occurrence_group_targets_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['event_occurrences.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_occurrence_group_targets_group_id_valid_from_valid_to', 'event_occurrence_group_targets', ['group_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_event_occurrence_group_targets_occ_id_valid_from_valid_to', 'event_occurrence_group_targets', ['occurrence_id', 'valid_from', 'valid_to'], unique=False)
    op.create_table('event_occurrence_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('registration_status', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_event_occurrence_participants_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['event_occurrences.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_occurrence_participants_occurrence_id', 'event_occurrence_participants', ['occurrence_id'], unique=False)
    op.create_index('ix_event_occurrence_participants_person_id', 'event_occurrence_participants', ['person_id'], unique=False)
    op.create_table('event_occurrence_staff_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurrence_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_event', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('occurrence_id'), '='), (sa.text('tstzrange(valid_from, valid_to)'), '&&'), where=sa.text('is_primary = true'), using='gist', name='ck_event_occurrence_staff_assignments_one_active_primary'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_event_occurrence_staff_assignments_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['event_occurrences.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_occurrence_staff_assignments_occurrence_id', 'event_occurrence_staff_assignments', ['occurrence_id'], unique=False)
    op.create_index('ix_event_occurrence_staff_assignments_user_id', 'event_occurrence_staff_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###

    op.drop_constraint('ck_audit_logs_action_valid', 'audit_logs', type_='check')
    op.create_check_constraint(
        'ck_audit_logs_action_valid', 'audit_logs', f'action IN ({_NEW_ACTION_VALUES})'
    )


def downgrade() -> None:
    op.drop_constraint('ck_audit_logs_action_valid', 'audit_logs', type_='check')
    op.create_check_constraint(
        'ck_audit_logs_action_valid', 'audit_logs', f'action IN ({_OLD_ACTION_VALUES})'
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_occurrence_staff_assignments_user_id', table_name='event_occurrence_staff_assignments')
    op.drop_index('ix_event_occurrence_staff_assignments_occurrence_id', table_name='event_occurrence_staff_assignments')
    op.drop_table('event_occurrence_staff_assignments')
    op.drop_index('ix_event_occurrence_participants_person_id', table_name='event_occurrence_participants')
    op.drop_index('ix_event_occurrence_participants_occurrence_id', table_name='event_occurrence_participants')
    op.drop_table('event_occurrence_participants')
    op.drop_index('ix_event_occurrence_group_targets_occ_id_valid_from_valid_to', table_name='event_occurrence_group_targets')
    op.drop_index('ix_event_occurrence_group_targets_group_id_valid_from_valid_to', table_name='event_occurrence_group_targets')
    op.drop_table('event_occurrence_group_targets')
    op.drop_index('ix_event_series_staff_assignments_user_id', table_name='event_series_staff_assignments')
    op.drop_index('ix_event_series_staff_assignments_event_series_id', table_name='event_series_staff_assignments')
    op.drop_table('event_series_staff_assignments')
    op.drop_index('ix_event_series_participants_person_id', table_name='event_series_participants')
    op.drop_index('ix_event_series_participants_event_series_id', table_name='event_series_participants')
    op.drop_table('event_series_participants')
    op.drop_index('ix_event_series_group_targets_series_id_valid_from_valid_to', table_name='event_series_group_targets')
    op.drop_index('ix_event_series_group_targets_group_id_valid_from_valid_to', table_name='event_series_group_targets')
    op.drop_table('event_series_group_targets')
    # ### end Alembic commands ###
