"""create inventory foundation tables

Revision ID: a3872eb0b9d7
Revises: e1462e9dc1b8
Create Date: 2026-09-30 18:04:15.350446

TH-0121 / Issue #230 (docs/04-domain/inventory.md):

- `inventory_categories`, `inventory_units`, `inventory_storage_locations`
  (self-referencing tree), `inventory_items` (nomenclature): closed
  `active`/`archived` lifecycle with `archived_at` tied to the status
  (CHECK), every FK RESTRICT — no physical deletion. Active-name
  uniqueness (G15) as partial unique indexes over `lower(name)`.
- `inventory_items` has no quantity/stock/state/location column; the
  current cost is `current_cost_minor` (RUB kopecks, >= 0, nullable).
- `inventory_movements`: the append-only movement journal (item, closed
  movement-type vocabulary, creator, time). No movement is created here.
- Seeds the four system units `шт`, `м`, `комплект`, `пара` (G11): no
  Club, no creator, permanently active (CHECK).

No permission is seeded and no role grant changes: Inventory is
Administrator-only through the existing canonical `admin` Role
recognition (inventory.md §3, G7). The closed audit action vocabulary
(ADR-0024 §4) is not touched (G10).
"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'a3872eb0b9d7'
down_revision: Union[str, None] = 'e1462e9dc1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# docs/04-domain/inventory.md §9 п.2 (G11). Duplicated from
# app.inventory.vocabulary.SYSTEM_UNIT_NAMES on purpose: a migration must
# not change meaning if application code later changes.
_SYSTEM_UNIT_NAMES = ("шт", "м", "комплект", "пара")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'archived') = (archived_at IS NOT NULL)", name='ck_inventory_categories_archived_at_matches_status'),
    sa.CheckConstraint("status IN ('active','archived')", name='ck_inventory_categories_status_valid'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_categories_club_id_status', 'inventory_categories', ['club_id', 'status'], unique=False)
    op.create_table('inventory_storage_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'archived') = (archived_at IS NOT NULL)", name='ck_inventory_storage_locations_archived_at_matches_status'),
    sa.CheckConstraint("status IN ('active','archived')", name='ck_inventory_storage_locations_status_valid'),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name='ck_inventory_storage_locations_not_own_parent'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory_storage_locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_storage_locations_club_id_status', 'inventory_storage_locations', ['club_id', 'status'], unique=False)
    op.create_index('ix_inventory_storage_locations_parent_id', 'inventory_storage_locations', ['parent_id'], unique=False)
    op.create_index('uq_inventory_storage_locations_active_child_name', 'inventory_storage_locations', ['parent_id', sa.text('lower(name)')], unique=True, postgresql_where=sa.text("status = 'active' AND parent_id IS NOT NULL"))
    op.create_index('uq_inventory_storage_locations_active_root_name', 'inventory_storage_locations', ['club_id', sa.text('lower(name)')], unique=True, postgresql_where=sa.text("status = 'active' AND parent_id IS NULL"))
    op.create_table('inventory_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'archived') = (archived_at IS NOT NULL)", name='ck_inventory_units_archived_at_matches_status'),
    sa.CheckConstraint("NOT is_system OR (club_id IS NULL AND created_by IS NULL AND status = 'active')", name='ck_inventory_units_system_unit_shape'),
    sa.CheckConstraint("status IN ('active','archived')", name='ck_inventory_units_status_valid'),
    sa.CheckConstraint('is_system OR (club_id IS NOT NULL AND created_by IS NOT NULL)', name='ck_inventory_units_custom_unit_shape'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_units_club_id_status', 'inventory_units', ['club_id', 'status'], unique=False)
    op.create_index('uq_inventory_units_system_name', 'inventory_units', [sa.text('lower(name)')], unique=True, postgresql_where=sa.text('is_system'))
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('accounting_mode', sa.String(length=16), nullable=False),
    sa.Column('current_cost_minor', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'archived') = (archived_at IS NOT NULL)", name='ck_inventory_items_archived_at_matches_status'),
    sa.CheckConstraint("accounting_mode IN ('instance','quantity')", name='ck_inventory_items_accounting_mode_valid'),
    sa.CheckConstraint("status IN ('active','archived')", name='ck_inventory_items_status_valid'),
    sa.CheckConstraint('current_cost_minor IS NULL OR current_cost_minor >= 0', name='ck_inventory_items_current_cost_minor_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['inventory_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_items_category_id', 'inventory_items', ['category_id'], unique=False)
    op.create_index('ix_inventory_items_club_id_status', 'inventory_items', ['club_id', 'status'], unique=False)
    op.create_index('ix_inventory_items_unit_id', 'inventory_items', ['unit_id'], unique=False)
    op.create_index('uq_inventory_items_active_name', 'inventory_items', ['club_id', sa.text('lower(name)')], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("movement_type IN ('adjustment','issue','receipt','return','transfer','write_off')", name='ck_inventory_movements_movement_type_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_movements_item_id_created_at', 'inventory_movements', ['item_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    units_table = sa.table(
        "inventory_units",
        sa.column("id", UUID(as_uuid=True)),
        sa.column("name", sa.String),
        sa.column("is_system", sa.Boolean),
        sa.column("status", sa.String),
    )
    op.get_bind().execute(
        units_table.insert().values(
            [
                {"id": uuid.uuid4(), "name": name, "is_system": True, "status": "active"}
                for name in _SYSTEM_UNIT_NAMES
            ]
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_movements_item_id_created_at', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('uq_inventory_items_active_name', table_name='inventory_items', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_inventory_items_unit_id', table_name='inventory_items')
    op.drop_index('ix_inventory_items_club_id_status', table_name='inventory_items')
    op.drop_index('ix_inventory_items_category_id', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('uq_inventory_units_system_name', table_name='inventory_units', postgresql_where=sa.text('is_system'))
    op.drop_index('ix_inventory_units_club_id_status', table_name='inventory_units')
    op.drop_table('inventory_units')
    op.drop_index('uq_inventory_storage_locations_active_root_name', table_name='inventory_storage_locations', postgresql_where=sa.text("status = 'active' AND parent_id IS NULL"))
    op.drop_index('uq_inventory_storage_locations_active_child_name', table_name='inventory_storage_locations', postgresql_where=sa.text("status = 'active' AND parent_id IS NOT NULL"))
    op.drop_index('ix_inventory_storage_locations_parent_id', table_name='inventory_storage_locations')
    op.drop_index('ix_inventory_storage_locations_club_id_status', table_name='inventory_storage_locations')
    op.drop_table('inventory_storage_locations')
    op.drop_index('ix_inventory_categories_club_id_status', table_name='inventory_categories')
    op.drop_table('inventory_categories')
    # ### end Alembic commands ###
