"""create inventory quantity stock

Revision ID: a80d82ba673f
Revises: 315a43d40d9b
Create Date: 2026-09-30 20:46:38.302209

Inventory Slice 3 — quantity movements (Issue #230,
docs/04-domain/inventory.md §6, §13, §16, §17):

- `inventory_movements.quantity`: set exactly on movements without an
  instance (CHECK) and positive (CHECK). Every existing movement belongs
  to an instance (Slice 2 is the only writer so far), so no row changes.
- `inventory_item_stocks`: current stock of a quantity item per storage
  location — a projection of the journal; `quantity >= 0` (CHECK), one row
  per (item, location) (UNIQUE), FK RESTRICT.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80d82ba673f'
down_revision: Union[str, None] = '315a43d40d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('storage_location_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_item_stocks_quantity_non_negative'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['inventory_storage_locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'storage_location_id', name='uq_inventory_item_stocks_item_id_storage_location_id')
    )
    op.create_index('ix_inventory_item_stocks_storage_location_id', 'inventory_item_stocks', ['storage_location_id'], unique=False)
    op.add_column('inventory_movements', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # CHECK constraints are not compared by autogenerate.
    op.create_check_constraint(
        'ck_inventory_movements_quantity_matches_instance',
        'inventory_movements',
        '(instance_id IS NULL) = (quantity IS NOT NULL)',
    )
    op.create_check_constraint(
        'ck_inventory_movements_quantity_positive',
        'inventory_movements',
        'quantity IS NULL OR quantity > 0',
    )


def downgrade() -> None:
    op.drop_constraint('ck_inventory_movements_quantity_positive', 'inventory_movements', type_='check')
    op.drop_constraint('ck_inventory_movements_quantity_matches_instance', 'inventory_movements', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_movements', 'quantity')
    op.drop_index('ix_inventory_item_stocks_storage_location_id', table_name='inventory_item_stocks')
    op.drop_table('inventory_item_stocks')
    # ### end Alembic commands ###
