"""create events table

Revision ID: a86214bd3bc4
Revises: d7e9e112d370
Create Date: 2026-09-13 02:49:43.821725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86214bd3bc4'
down_revision: Union[str, None] = 'd7e9e112d370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('location_type', sa.String(length=32), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('location_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('lesson','training','trip','competition','tour_slet','excursion','meeting','other')", name='ck_events_event_type_valid'),
    sa.CheckConstraint("status <> 'cancelled' OR cancellation_reason IS NOT NULL", name='ck_events_cancellation_reason_required_when_cancelled'),
    sa.CheckConstraint("status IN ('draft','published','in_progress','completed','cancelled','archived')", name='ck_events_status_valid'),
    sa.CheckConstraint('(location_latitude IS NULL) = (location_longitude IS NULL)', name='ck_events_location_coordinates_consistent'),
    sa.CheckConstraint('end_at > start_at', name='ck_events_end_at_after_start_at'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_club_id_start_at', 'events', ['club_id', 'start_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_club_id_start_at', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
