"""create achievement domain tables and seed achievement.manage

Revision ID: b7e3d1a9c5f2
Revises: 7d2b4e9f1a63
Create Date: 2026-10-04 20:24:06.952334

Issue #220 (Achievement Engine & Normative Management), canonical source
docs/04-modules/achievements-and-norms.md (A1-A12):

- creates the Achievement Domain tables — Definitions, Rule Versions,
  Normative Requirement Sets / Versions and Awards (see
  app.db.achievements for every invariant). Nothing is seeded into them:
  no Definition, Rule or Normative Set Version — in particular the FSTR
  reference snapshot (§8) is never loaded or activated;
- seeds the canonical permission `achievement.manage` (§25, A10) and
  grants it to `admin` only, with `all` scope. `achievement.award` /
  `achievement.read` already exist and are already granted to `admin`
  with `all` (6a99a77234ba + 20e1297d4e1a); no other role receives any
  achievement grant.

## Idempotency

Every seed insert uses `ON CONFLICT ... DO NOTHING` against its unique
constraint, like 3c1e9a7d5b20.

## Rollback

Drops the tables (Awards are historical records: the downgrade is meant
for an installation that has not issued any yet) and removes only the
`(admin, achievement.manage)` grant; the `permissions` row itself stays —
catalog data is stable, per the f85df8d36f12 / 95487f3b616b precedent.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7e3d1a9c5f2'
down_revision: Union[str, None] = '7d2b4e9f1a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PERMISSION_CODE = "achievement.manage"
_PERMISSION_DESCRIPTION = (
    "Manage Achievement Definitions, Rule Versions and Normative Requirement Sets"
)
_ROLE_CODE = "admin"
_SCOPE_TYPE = "all"


def _seed_permission() -> None:
    bind = op.get_bind()
    bind.execute(
        sa.text(
            """
            INSERT INTO permissions (id, code, description)
            VALUES (gen_random_uuid(), :code, :description)
            ON CONFLICT (code) DO NOTHING
            """
        ),
        {"code": _PERMISSION_CODE, "description": _PERMISSION_DESCRIPTION},
    )
    params = {"role_code": _ROLE_CODE, "permission_code": _PERMISSION_CODE}
    bind.execute(
        sa.text(
            """
            INSERT INTO role_permissions (id, role_id, permission_id)
            SELECT gen_random_uuid(), r.id, p.id
            FROM roles r, permissions p
            WHERE r.code = :role_code AND p.code = :permission_code
            ON CONFLICT (role_id, permission_id) DO NOTHING
            """
        ),
        params,
    )
    bind.execute(
        sa.text(
            """
            INSERT INTO role_permission_scopes (id, role_permission_id, scope_type)
            SELECT gen_random_uuid(), rp.id, :scope_type
            FROM role_permissions rp
            JOIN roles r ON r.id = rp.role_id
            JOIN permissions p ON p.id = rp.permission_id
            WHERE r.code = :role_code AND p.code = :permission_code
            ON CONFLICT (role_permission_id, scope_type) DO NOTHING
            """
        ),
        {**params, "scope_type": _SCOPE_TYPE},
    )


def _unseed_grant() -> None:
    op.get_bind().execute(
        sa.text(
            """
            DELETE FROM role_permissions rp
            USING roles r, permissions p
            WHERE rp.role_id = r.id
              AND rp.permission_id = p.id
              AND r.code = :role_code
              AND p.code = :permission_code
            """
        ),
        {"role_code": _ROLE_CODE, "permission_code": _PERMISSION_CODE},
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('award_method', sa.String(length=16), nullable=False),
    sa.Column('repeatability', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("award_method IN ('automatic', 'manual', 'both')", name='ck_achievement_definitions_award_method'),
    sa.CheckConstraint("repeatability IN ('non_repeatable', 'repeatable')", name='ck_achievement_definitions_repeatability'),
    sa.CheckConstraint("source IN ('club', 'fstr')", name='ck_achievement_definitions_source'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_achievement_definitions_status'),
    sa.CheckConstraint('length(btrim(code)) > 0', name='ck_achievement_definitions_code'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_achievement_definitions_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_achievement_definitions_code'),
    sa.UniqueConstraint('id', 'repeatability', name='uq_achievement_definitions_id_repeat')
    )
    op.create_table('achievement_normative_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name='ck_achievement_normative_sets_code'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_achievement_normative_sets_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_achievement_normative_sets_code')
    )
    op.create_table('achievement_normative_set_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('normative_set_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_organization', sa.String(length=255), nullable=False),
    sa.Column('document_title', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('document_version', sa.String(length=255), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_achievement_normative_set_versions_status'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_achievement_normative_set_versions_effective_range'),
    sa.CheckConstraint('length(btrim(source_organization)) > 0 AND length(btrim(document_title)) > 0 AND length(btrim(source_url)) > 0 AND length(btrim(document_version)) > 0', name='ck_achievement_normative_set_versions_metadata'),
    sa.CheckConstraint('version_number > 0', name='ck_achievement_normative_set_versions_number'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_achievement_normative_set_versions_created_by', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['normative_set_id'], ['achievement_normative_sets.id'], name='fk_achievement_normative_set_versions_set', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normative_set_id', 'version_number', name='uq_achievement_normative_set_versions_number')
    )
    op.create_table('achievement_rule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normative_set_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(condition) = 'object'", name='ck_achievement_rule_versions_condition'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_achievement_rule_versions_status'),
    sa.CheckConstraint('version_number > 0', name='ck_achievement_rule_versions_number'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_achievement_rule_versions_created_by', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['definition_id'], ['achievement_definitions.id'], name='fk_achievement_rule_versions_definition', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['normative_set_version_id'], ['achievement_normative_set_versions.id'], name='fk_achievement_rule_versions_normative_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'version_number', name='uq_achievement_rule_versions_number'),
    sa.UniqueConstraint('id', 'definition_id', name='uq_achievement_rule_versions_id_def')
    )
    op.create_index('uq_achievement_rule_versions_one_active', 'achievement_rule_versions', ['definition_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('achievement_awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('definition_repeatability', sa.String(length=16), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('award_method', sa.String(length=16), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=True),
    sa.Column('normative_set_version_id', sa.UUID(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('awarded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('evaluation_trigger', sa.String(length=32), nullable=True),
    sa.Column('evaluated_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(award_method = 'automatic' AND rule_version_id IS NOT NULL AND evaluation_trigger IS NOT NULL AND awarded_by_user_id IS NULL AND verification_note IS NULL) OR (award_method = 'manual' AND awarded_by_user_id IS NOT NULL AND evaluation_trigger IS NULL AND evaluated_metrics IS NULL)", name='ck_achievement_awards_method_provenance'),
    sa.CheckConstraint("(status = 'active' AND revoked_at IS NULL AND revoked_by_user_id IS NULL AND revocation_reason IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL AND revocation_reason IS NOT NULL AND length(btrim(revocation_reason)) > 0)", name='ck_achievement_awards_revocation'),
    sa.CheckConstraint("award_method <> 'automatic' OR definition_repeatability = 'non_repeatable'", name='ck_achievement_awards_no_automatic_repeatable'),
    sa.CheckConstraint("award_method IN ('automatic', 'manual')", name='ck_achievement_awards_award_method'),
    sa.CheckConstraint("evaluation_trigger IS NULL OR evaluation_trigger IN ('event', 'reconciliation')", name='ck_achievement_awards_evaluation_trigger'),
    sa.CheckConstraint("status IN ('active', 'revoked')", name='ck_achievement_awards_status'),
    sa.ForeignKeyConstraint(['awarded_by_user_id'], ['users.id'], name='fk_achievement_awards_awarded_by', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['definition_id', 'definition_repeatability'], ['achievement_definitions.id', 'achievement_definitions.repeatability'], name='fk_achievement_awards_definition', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['normative_set_version_id'], ['achievement_normative_set_versions.id'], name='fk_achievement_awards_normative_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name='fk_achievement_awards_person', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], name='fk_achievement_awards_revoked_by', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_version_id', 'definition_id'], ['achievement_rule_versions.id', 'achievement_rule_versions.definition_id'], name='fk_achievement_awards_rule_version', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_achievement_awards_normative_set_version_id', 'achievement_awards', ['normative_set_version_id'], unique=False)
    op.create_index('ix_achievement_awards_person_id', 'achievement_awards', ['person_id'], unique=False)
    op.create_index('ix_achievement_awards_rule_version_id', 'achievement_awards', ['rule_version_id'], unique=False)
    op.create_index('uq_achievement_awards_non_repeatable', 'achievement_awards', ['definition_id', 'person_id'], unique=True, postgresql_where=sa.text("definition_repeatability = 'non_repeatable'"))
    # ### end Alembic commands ###
    _seed_permission()


def downgrade() -> None:
    _unseed_grant()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_achievement_awards_non_repeatable', table_name='achievement_awards', postgresql_where=sa.text("definition_repeatability = 'non_repeatable'"))
    op.drop_index('ix_achievement_awards_rule_version_id', table_name='achievement_awards')
    op.drop_index('ix_achievement_awards_person_id', table_name='achievement_awards')
    op.drop_index('ix_achievement_awards_normative_set_version_id', table_name='achievement_awards')
    op.drop_table('achievement_awards')
    op.drop_index('uq_achievement_rule_versions_one_active', table_name='achievement_rule_versions', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('achievement_rule_versions')
    op.drop_table('achievement_normative_set_versions')
    op.drop_table('achievement_normative_sets')
    op.drop_table('achievement_definitions')
    # ### end Alembic commands ###
