"""create group persistence tables

Revision ID: b8792b2e655f
Revises: a86214bd3bc4
Create Date: 2026-09-13 04:25:39.262235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b8792b2e655f'
down_revision: Union[str, None] = 'a86214bd3bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_groups_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_groups_club_id', 'groups', ['club_id'], unique=False)
    op.create_table('group_instructor_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_group', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_group_instructor_assignments_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_group_instructor_assignments_group_id', 'group_instructor_assignments', ['group_id'], unique=False)
    op.create_index('ix_group_instructor_assignments_user_id', 'group_instructor_assignments', ['user_id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('club_membership_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('membership_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_group_memberships_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['club_membership_id'], ['club_memberships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_group_memberships_club_membership_id', 'group_memberships', ['club_membership_id'], unique=False)
    op.create_index('ix_group_memberships_group_id_valid_from_valid_to', 'group_memberships', ['group_id', 'valid_from', 'valid_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_group_memberships_group_id_valid_from_valid_to', table_name='group_memberships')
    op.drop_index('ix_group_memberships_club_membership_id', table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index('ix_group_instructor_assignments_user_id', table_name='group_instructor_assignments')
    op.drop_index('ix_group_instructor_assignments_group_id', table_name='group_instructor_assignments')
    op.drop_table('group_instructor_assignments')
    op.drop_index('ix_groups_club_id', table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
