"""add club membership indexes and extend audit action vocabulary

Revision ID: b99fd408c104
Revises: ea00553ae97a
Create Date: 2026-09-13 20:11:36.432426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99fd408c104'
down_revision: Union[str, None] = 'ea00553ae97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ADR-0025 §1 amends ADR-0024 §4's closed audit action vocabulary to add
# person.created/person.updated/person.archived, and Issue #62's accepted
# decisions add membership.updated (non-lifecycle ClubMembership attribute
# changes, e.g. membership_type). Alembic's autogenerate does not diff
# CHECK constraint bodies, so the constraint swap below is hand-written,
# not autogenerated; the index commands above it are the autogenerated
# part for the new club_memberships indexes.
_OLD_ACTION_VALUES = (
    "'event.archived','event.created','event.status_changed','event.updated',"
    "'group.created','group.updated','group_instructor_assignment.created',"
    "'group_instructor_assignment.ended','group_instructor_assignment.updated',"
    "'group_membership.created','group_membership.ended','group_membership.updated',"
    "'guardian_relationship.created','guardian_relationship.revoked',"
    "'guardian_relationship.updated','membership.created','membership.ended',"
    "'membership.status_changed','role_assignment.changed','role_assignment.created',"
    "'role_assignment.revoked','user.created','user.locked','user.status_changed',"
    "'user.unlocked'"
)
_NEW_ACTION_VALUES = (
    "'event.archived','event.created','event.status_changed','event.updated',"
    "'group.created','group.updated','group_instructor_assignment.created',"
    "'group_instructor_assignment.ended','group_instructor_assignment.updated',"
    "'group_membership.created','group_membership.ended','group_membership.updated',"
    "'guardian_relationship.created','guardian_relationship.revoked',"
    "'guardian_relationship.updated','membership.created','membership.ended',"
    "'membership.status_changed','membership.updated','person.archived',"
    "'person.created','person.updated','role_assignment.changed',"
    "'role_assignment.created','role_assignment.revoked','user.created','user.locked',"
    "'user.status_changed','user.unlocked'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_club_memberships_club_id_status', 'club_memberships', ['club_id', 'status'], unique=False)
    op.create_index('ix_club_memberships_person_id', 'club_memberships', ['person_id'], unique=False)
    # ### end Alembic commands ###

    op.drop_constraint('ck_audit_logs_action_valid', 'audit_logs', type_='check')
    op.create_check_constraint(
        'ck_audit_logs_action_valid', 'audit_logs', f'action IN ({_NEW_ACTION_VALUES})'
    )


def downgrade() -> None:
    op.drop_constraint('ck_audit_logs_action_valid', 'audit_logs', type_='check')
    op.create_check_constraint(
        'ck_audit_logs_action_valid', 'audit_logs', f'action IN ({_OLD_ACTION_VALUES})'
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_club_memberships_person_id', table_name='club_memberships')
    op.drop_index('ix_club_memberships_club_id_status', table_name='club_memberships')
    # ### end Alembic commands ###
