"""create tourism types and trip tourism type

Revision ID: c4f8a2e61d93
Revises: b7e3d1a9c5f2
Create Date: 2026-10-05 10:51:19.825360

Issue #264 (Tourism Facts v2 — TourismType Foundation), canonical source
docs/04-modules/trips-and-tourist-profile.md §3 (Issue #256):

- creates the `tourism_types` reference catalog (`code` unique, `name`,
  `active`). Deliberately NO seed rows: the concrete catalog values are
  not approved;
- adds the nullable `trips.tourism_type_id` FK (ON DELETE/UPDATE
  RESTRICT) so a TourismType referenced by any Trip can never be
  physically deleted. Existing Trip rows keep `NULL`.

No permission is seeded: TourismType reuses `trip.read`/`trip.manage`.

Downgrade drops the column and the catalog (meant for an installation
that has not yet relied on the catalog).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f8a2e61d93'
down_revision: Union[str, None] = 'b7e3d1a9c5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourism_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name='ck_tourism_types_code_not_blank'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_tourism_types_name_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_tourism_types_code')
    )
    op.add_column('trips', sa.Column('tourism_type_id', sa.UUID(), nullable=True))
    op.create_index('ix_trips_tourism_type_id', 'trips', ['tourism_type_id'], unique=False)
    op.create_foreign_key('fk_trips_tourism_type_id', 'trips', 'tourism_types', ['tourism_type_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_trips_tourism_type_id', 'trips', type_='foreignkey')
    op.drop_index('ix_trips_tourism_type_id', table_name='trips')
    op.drop_column('trips', 'tourism_type_id')
    op.drop_table('tourism_types')
    # ### end Alembic commands ###
