"""create inventory issues

Revision ID: ceae7e0687cb
Revises: a80d82ba673f
Create Date: 2026-10-02 16:38:41.312648

Inventory Slice 4 — issue / return (Issue #236,
docs/04-domain/inventory.md §14, §17):

- `inventory_issues`: the issue document — one recipient (Member ->
  `persons`, Instructor -> `users`, Group -> `groups`; exactly the column
  of `recipient_type` is set, CHECK), optional Event, informational
  planned return date, comment, `issued` | `cancelled` (cancellation
  columns set exactly when cancelled, CHECK).
- `inventory_issue_lines`: one active line per item of an issue (partial
  UNIQUE `issue_id, item_id` WHERE `removed_at IS NULL`); a line with
  nothing outstanding can be removed from the issue — `removed_at` /
  `removed_by` (both or neither, CHECK) — and the row stays, so movements
  keep referencing it; `(id, item_id)` is UNIQUE as the target of the
  movements' composite FK.
- `inventory_movements.issue_line_id`: required on `issue`/`return`,
  allowed on `write_off` (the write-off half of a lost instance), absent on
  every other type (CHECK); FK `(issue_line_id, item_id)` keeps a movement
  on a line of its own item. No existing movement is an `issue`/`return`
  (no earlier slice wrote them), so no row changes.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceae7e0687cb'
down_revision: Union[str, None] = 'a80d82ba673f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.String(length=16), nullable=False),
    sa.Column('recipient_person_id', sa.UUID(), nullable=True),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_group_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('planned_return_date', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(recipient_type = 'member') = (recipient_person_id IS NOT NULL) AND (recipient_type = 'instructor') = (recipient_user_id IS NOT NULL) AND (recipient_type = 'group') = (recipient_group_id IS NOT NULL)", name='ck_inventory_issues_recipient_matches_type'),
    sa.CheckConstraint("(status = 'cancelled') = (cancelled_at IS NOT NULL) AND (status = 'cancelled') = (cancelled_by IS NOT NULL)", name='ck_inventory_issues_cancellation_matches_status'),
    sa.CheckConstraint("recipient_type IN ('group','instructor','member')", name='ck_inventory_issues_recipient_type_valid'),
    sa.CheckConstraint("status IN ('cancelled','issued')", name='ck_inventory_issues_status_valid'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_issues_club_id_status', 'inventory_issues', ['club_id', 'status'], unique=False)
    op.create_index('ix_inventory_issues_event_id', 'inventory_issues', ['event_id'], unique=False)
    op.create_index('ix_inventory_issues_recipient_group_id', 'inventory_issues', ['recipient_group_id'], unique=False)
    op.create_index('ix_inventory_issues_recipient_person_id', 'inventory_issues', ['recipient_person_id'], unique=False)
    op.create_index('ix_inventory_issues_recipient_user_id', 'inventory_issues', ['recipient_user_id'], unique=False)
    op.create_table('inventory_issue_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('(removed_at IS NULL) = (removed_by IS NULL)', name='ck_inventory_issue_lines_removed_by_matches_removed_at'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_id'], ['inventory_issues.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['removed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'item_id', name='uq_inventory_issue_lines_id_item_id')
    )
    op.create_index('ix_inventory_issue_lines_issue_id', 'inventory_issue_lines', ['issue_id'], unique=False)
    op.create_index('ix_inventory_issue_lines_item_id', 'inventory_issue_lines', ['item_id'], unique=False)
    op.create_index('uq_inventory_issue_lines_active_issue_id_item_id', 'inventory_issue_lines', ['issue_id', 'item_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.add_column('inventory_movements', sa.Column('issue_line_id', sa.UUID(), nullable=True))
    op.create_index('ix_inventory_movements_issue_line_id', 'inventory_movements', ['issue_line_id'], unique=False)
    op.create_foreign_key('fk_inventory_movements_issue_line_id_item_id', 'inventory_movements', 'inventory_issue_lines', ['issue_line_id', 'item_id'], ['id', 'item_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###

    # CHECK constraints are not compared by autogenerate.
    op.create_check_constraint(
        'ck_inventory_movements_issue_line_reference',
        'inventory_movements',
        "(movement_type IN ('issue','return') AND issue_line_id IS NOT NULL)"
        " OR (movement_type NOT IN ('issue','return')"
        " AND (issue_line_id IS NULL OR movement_type = 'write_off'))",
    )


def downgrade() -> None:
    op.drop_constraint('ck_inventory_movements_issue_line_reference', 'inventory_movements', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_inventory_movements_issue_line_id_item_id', 'inventory_movements', type_='foreignkey')
    op.drop_index('ix_inventory_movements_issue_line_id', table_name='inventory_movements')
    op.drop_column('inventory_movements', 'issue_line_id')
    op.drop_index('uq_inventory_issue_lines_active_issue_id_item_id', table_name='inventory_issue_lines', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index('ix_inventory_issue_lines_item_id', table_name='inventory_issue_lines')
    op.drop_index('ix_inventory_issue_lines_issue_id', table_name='inventory_issue_lines')
    op.drop_table('inventory_issue_lines')
    op.drop_index('ix_inventory_issues_recipient_user_id', table_name='inventory_issues')
    op.drop_index('ix_inventory_issues_recipient_person_id', table_name='inventory_issues')
    op.drop_index('ix_inventory_issues_recipient_group_id', table_name='inventory_issues')
    op.drop_index('ix_inventory_issues_event_id', table_name='inventory_issues')
    op.drop_index('ix_inventory_issues_club_id_status', table_name='inventory_issues')
    op.drop_table('inventory_issues')
    # ### end Alembic commands ###
