"""create guardian relationship table

Revision ID: d0023b757548
Revises: 2ba3556a97ce
Create Date: 2026-09-13 13:03:04.385665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0023b757548'
down_revision: Union[str, None] = '2ba3556a97ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guardian_person_id', sa.UUID(), nullable=False),
    sa.Column('child_person_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('child_person_id'), '='), (sa.text('tstzrange(valid_from, valid_to)'), '&&'), where=sa.text("is_primary_contact = true AND status = 'active'"), using='gist', name='ck_guardian_relationships_no_overlapping_primary_contact'),
    postgresql.ExcludeConstraint((sa.column('guardian_person_id'), '='), (sa.column('child_person_id'), '='), (sa.column('relationship_type'), '='), (sa.text('tstzrange(valid_from, valid_to)'), '&&'), where=sa.text("status = 'active'"), using='gist', name='ck_guardian_relationships_no_overlapping_active'),
    sa.CheckConstraint("status IN ('active','inactive','revoked')", name='ck_guardian_relationships_status_valid'),
    sa.CheckConstraint('guardian_person_id <> child_person_id', name='ck_guardian_relationships_guardian_child_distinct'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_guardian_relationships_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['child_person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['guardian_person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guardian_relationships_child_valid', 'guardian_relationships', ['child_person_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_guardian_relationships_guardian_valid', 'guardian_relationships', ['guardian_person_id', 'valid_from', 'valid_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_guardian_relationships_guardian_valid', table_name='guardian_relationships')
    op.drop_index('ix_guardian_relationships_child_valid', table_name='guardian_relationships')
    op.drop_table('guardian_relationships')
    # ### end Alembic commands ###
