"""create authentication persistence tables

Revision ID: d7e9e112d370
Revises: e5ae1ad9e1e1
Create Date: 2026-09-12 21:23:43.441726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e9e112d370'
down_revision: Union[str, None] = 'e5ae1ad9e1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authenticated_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('created_ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_user_agent', sa.Text(), nullable=True),
    sa.Column('last_seen_ip_address', sa.String(length=64), nullable=True),
    sa.CheckConstraint("status <> 'revoked' OR revoked_at IS NOT NULL", name='ck_authenticated_sessions_revoked_at_when_revoked'),
    sa.CheckConstraint("status IN ('active','revoked','expired')", name='ck_authenticated_sessions_status_valid'),
    sa.CheckConstraint('expires_at > created_at', name='ck_authenticated_sessions_expires_after_created'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token_hash')
    )
    op.create_index('ix_authenticated_sessions_expires_at_status', 'authenticated_sessions', ['expires_at', 'status'], unique=False)
    op.create_index('ix_authenticated_sessions_user_id_status', 'authenticated_sessions', ['user_id', 'status'], unique=False)
    op.create_table('email_verification_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_email_verification_challenges_user_id_consumed_revoked', 'email_verification_challenges', ['user_id', 'consumed_at', 'revoked_at'], unique=False)
    op.create_index('ix_email_verification_challenges_user_id_expires_at', 'email_verification_challenges', ['user_id', 'expires_at'], unique=False)
    op.create_table('password_reset_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_password_reset_challenges_user_id_consumed_revoked', 'password_reset_challenges', ['user_id', 'consumed_at', 'revoked_at'], unique=False)
    op.create_index('ix_password_reset_challenges_user_id_expires_at', 'password_reset_challenges', ['user_id', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_password_reset_challenges_user_id_expires_at', table_name='password_reset_challenges')
    op.drop_index('ix_password_reset_challenges_user_id_consumed_revoked', table_name='password_reset_challenges')
    op.drop_table('password_reset_challenges')
    op.drop_index('ix_email_verification_challenges_user_id_expires_at', table_name='email_verification_challenges')
    op.drop_index('ix_email_verification_challenges_user_id_consumed_revoked', table_name='email_verification_challenges')
    op.drop_table('email_verification_challenges')
    op.drop_index('ix_authenticated_sessions_user_id_status', table_name='authenticated_sessions')
    op.drop_index('ix_authenticated_sessions_expires_at_status', table_name='authenticated_sessions')
    op.drop_table('authenticated_sessions')
    # ### end Alembic commands ###
