"""create news tables

Revision ID: e1462e9dc1b8
Revises: 127da2741f20
Create Date: 2026-09-30 13:28:33.664369

TH-0120 / Issue #227 (docs/04-ux/news.md):

- `news`: one Club-owned announcement — required title/body, closed
  `draft`/`published`/`archived` status (CHECK), `club`/`groups` audience
  type (CHECK), system `published_at`/`archived_at` (CHECK-tied to the
  status), optional `event_date`/`location`, optional linked Event
  (`event_id` -> events) and optional image (`image_file_id` -> the
  existing `files` table, binary behind FileStorage), created/updated
  metadata. Every FK is RESTRICT: News is never physically deleted.
- `news_group_targets`: the selected Groups of a `groups`-audience News
  (targeting configuration, same shape as `event_group_targets`; not an
  audience-membership table — readers are resolved at read time from the
  existing group/guardian/instructor relationships).

No permission is seeded and no role grant changes: News mutations are
Administrator-only through the existing canonical `admin` Role
recognition (news.md §9 — no new permission). The closed audit action
vocabulary (ADR-0024 §4) is not touched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1462e9dc1b8'
down_revision: Union[str, None] = '127da2741f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('audience_type', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('image_file_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("audience_type IN ('club','groups')", name='ck_news_audience_type_valid'),
    sa.CheckConstraint("status <> 'archived' OR archived_at IS NOT NULL", name='ck_news_archived_has_archived_at'),
    sa.CheckConstraint("status <> 'published' OR published_at IS NOT NULL", name='ck_news_published_has_published_at'),
    sa.CheckConstraint("status IN ('archived','draft','published')", name='ck_news_status_valid'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['image_file_id'], ['files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_club_id_status_published_at', 'news', ['club_id', 'status', 'published_at'], unique=False)
    op.create_index('ix_news_event_id', 'news', ['event_id'], unique=False)
    op.create_table('news_group_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('news_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'group_id', name='uq_news_group_targets_news_id_group_id')
    )
    op.create_index('ix_news_group_targets_group_id', 'news_group_targets', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_group_targets_group_id', table_name='news_group_targets')
    op.drop_table('news_group_targets')
    op.drop_index('ix_news_event_id', table_name='news')
    op.drop_index('ix_news_club_id_status_published_at', table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
