"""create event staff assignment table

Revision ID: e5859c9b98a6
Revises: b8792b2e655f
Create Date: 2026-09-13 09:11:53.517394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5859c9b98a6'
down_revision: Union[str, None] = 'b8792b2e655f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_staff_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_event', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('event_id'), '='), (sa.text('tstzrange(valid_from, valid_to)'), '&&'), where=sa.text('is_primary = true'), using='gist', name='ck_event_staff_assignments_one_active_primary'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_event_staff_assignments_valid_to_after_valid_from'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_staff_assignments_event_id', 'event_staff_assignments', ['event_id'], unique=False)
    op.create_index('ix_event_staff_assignments_user_id', 'event_staff_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_staff_assignments_user_id', table_name='event_staff_assignments')
    op.drop_index('ix_event_staff_assignments_event_id', table_name='event_staff_assignments')
    op.drop_table('event_staff_assignments')
    # ### end Alembic commands ###
