"""create role permission and role assignment tables

Revision ID: e5ae1ad9e1e1
Revises: 80dd15675404
Create Date: 2026-09-12 19:09:13.660691

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, insert as pg_insert


# revision identifiers, used by Alembic.
revision: str = 'e5ae1ad9e1e1'
down_revision: Union[str, None] = '80dd15675404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# database-schema.md §28 ("Initial reference domains include: roles;
# permissions; ...") + Issue #19 §9: seed the baseline role and permission
# catalogs only. No RolePermission grants are seeded — mapping the
# roles-and-permissions.md §7 matrix ("assigned/owned", "по permission", ...)
# into concrete grants is a product decision, not a persistence-foundation
# detail, and is deliberately left for a future issue (see final report).
_BASELINE_ROLES = (
    ("admin", "Admin", True),
    ("instructor", "Instructor", True),
    ("member", "Member", True),
    ("guardian", "Guardian", True),
)

_DOCUMENTED_PERMISSIONS = (
    "person.read",
    "person.update",
    "membership.read",
    "membership.manage",
    "group.read",
    "group.manage",
    "event.read",
    "event.create",
    "event.update",
    "event.cancel",
    "event.manage",
    "attendance.read",
    "attendance.update",
    "trip.read",
    "trip.manage",
    "achievement.read",
    "achievement.award",
    "knowledge.read",
    "knowledge.manage",
    "document.read",
    "document.manage",
    "consent.read",
    "consent.manage",
    "equipment.read",
    "equipment.manage",
    "finance.read",
    "finance.manage",
    "notification.read",
    "notification.manage",
    "audit.read",
    "settings.manage",
    "role.manage",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_ref_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope_type IN ('all','self','children','own_groups','own_events','none')", name='ck_user_role_assignments_scope_type_valid'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'club_id', 'scope_type', 'scope_ref_id', name='uq_user_role_assignments_no_duplicate', postgresql_nulls_not_distinct=True)
    )
    # ### end Alembic commands ###

    # Seed the baseline role/permission catalogs (database-schema.md §28,
    # §27 "seed/reference data must be versioned and reproducible"). IDs are
    # generated here in Python (ADR-0010: application-generated UUIDs), and
    # the insert is idempotent (`ON CONFLICT (code) DO NOTHING`) per Issue
    # #19 §9/§14, matching this table's own `code` uniqueness constraint.
    roles_table = sa.table(
        "roles",
        sa.column("id", UUID(as_uuid=True)),
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("is_system", sa.Boolean),
    )
    permissions_table = sa.table(
        "permissions",
        sa.column("id", UUID(as_uuid=True)),
        sa.column("code", sa.String),
    )

    bind = op.get_bind()
    bind.execute(
        pg_insert(roles_table)
        .values(
            [
                {"id": uuid.uuid4(), "code": code, "name": name, "is_system": is_system}
                for code, name, is_system in _BASELINE_ROLES
            ]
        )
        .on_conflict_do_nothing(index_elements=["code"])
    )
    bind.execute(
        pg_insert(permissions_table)
        .values([{"id": uuid.uuid4(), "code": code} for code in _DOCUMENTED_PERMISSIONS])
        .on_conflict_do_nothing(index_elements=["code"])
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_assignments')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
