"""create audit log table

Revision ID: ea00553ae97a
Revises: f4a149508ed0
Create Date: 2026-09-13 18:21:44.358266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea00553ae97a'
down_revision: Union[str, None] = 'f4a149508ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(actor_type = 'user' AND actor_user_id IS NOT NULL) OR (actor_type = 'system' AND actor_user_id IS NULL)", name='ck_audit_logs_actor_user_id_consistent'),
    sa.CheckConstraint("action IN ('event.archived','event.created','event.status_changed','event.updated','group.created','group.updated','group_instructor_assignment.created','group_instructor_assignment.ended','group_instructor_assignment.updated','group_membership.created','group_membership.ended','group_membership.updated','guardian_relationship.created','guardian_relationship.revoked','guardian_relationship.updated','membership.created','membership.ended','membership.status_changed','role_assignment.changed','role_assignment.created','role_assignment.revoked','user.created','user.locked','user.status_changed','user.unlocked')", name='ck_audit_logs_action_valid'),
    sa.CheckConstraint("actor_type IN ('system','user')", name='ck_audit_logs_actor_type_valid'),
    sa.CheckConstraint("outcome IN ('failure','success')", name='ck_audit_logs_outcome_valid'),
    sa.CheckConstraint('(resource_type IS NULL) = (resource_id IS NULL)', name='ck_audit_logs_resource_consistent'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_club_id', 'audit_logs', ['club_id'], unique=False)
    op.create_index('ix_audit_logs_occurred_at', 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_resource_type_resource_id', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_resource_type_resource_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_occurred_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_club_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
