"""create trip and trip participant tables

Revision ID: f6527395ba00
Revises: ceae7e0687cb
Create Date: 2026-10-04 15:14:37.733691

Issue #245 (TH-012x) — tourism-fact foundation, per the PO/CTO decisions
recorded on the Issue (see app.db.trips for the full model rationale):

- `trips`: 1:0..1 extension of an ordinary Event. `event_id` is the PK;
  `event_type` is CHECKed to `'trip'` and, with `event_id`, forms the
  composite FK to `events(id, event_type)` (ON UPDATE / ON DELETE
  RESTRICT) — BR-TRIP-001 enforced by the database. No tourism attribute
  columns (all deferred), no lifecycle column (the Event's is the only
  one).
- `trip_participants`: 1:0..1 extension of an EventParticipation of the
  Trip's Event. `event_participation_id` is the PK; the composite FK
  `(event_id, event_participation_id) -> event_participations(event_id,
  id)` keeps it on the same Event, `event_id -> trips.event_id` requires
  the Trip. No person_id / registration_status / participation_status
  column; every FK is RESTRICT (no cascade).
- `uq_events_id_event_type` / `uq_event_participations_event_id_id`: the
  minimal UNIQUE targets PostgreSQL requires for the two composite FKs.
  Both extend an already-unique `id`, so no existing row can violate
  them.

Alembic autogenerate emitted the two UNIQUE constraints after the
tables; they are moved before them here because a FK needs its target
constraint to exist first.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6527395ba00'
down_revision: Union[str, None] = 'ceae7e0687cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_events_id_event_type', 'events', ['id', 'event_type'])
    op.create_unique_constraint('uq_event_participations_event_id_id', 'event_participations', ['event_id', 'id'])
    op.create_table('trips',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type = 'trip'", name='ck_trips_event_type_trip'),
    sa.ForeignKeyConstraint(['event_id', 'event_type'], ['events.id', 'events.event_type'], name='fk_trips_event_id_event_type', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id', name='pk_trips')
    )
    op.create_table('trip_participants',
    sa.Column('event_participation_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('actual_participation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id', 'event_participation_id'], ['event_participations.event_id', 'event_participations.id'], name='fk_trip_participants_event_participation', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['trips.event_id'], name='fk_trip_participants_event_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_participation_id', name='pk_trip_participants')
    )
    op.create_index('ix_trip_participants_event_id', 'trip_participants', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_participants_event_id', table_name='trip_participants')
    op.drop_table('trip_participants')
    op.drop_table('trips')
    op.drop_constraint('uq_event_participations_event_id_id', 'event_participations', type_='unique')
    op.drop_constraint('uq_events_id_event_type', 'events', type_='unique')
    # ### end Alembic commands ###
